version: '2.3'

# create default network
networks:
  default:
    external:
      name: ros-network

services:

  odrive:
    build: ./image
    image: wn1980/odrive-ros${TAG}
    container_name: ros_odrive
    init: true
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - ROS_MASTER_URI=http://master:11311   
    #command: "roscore" 
