version: '2.3'

# create default network
networks:
  default:
    external:
      name: ros-network

services:

  odrive:
    build: ./image
    image: wn1980/odrive-ros${TAG}
    container_name: ros_odrive
    init: true
    restart: unless-stopped
    privileged: true
    devices:
      - "/dev:/dev"
    volumes:
      - "/dev:/dev"
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      - ROS_MASTER_URI=http://master:11311
      - WHEEL_TRACK=0.375 #m
      - TYRE_CIRCUMFERENCE=0.518 #m
      - USE_PREROLL=false
      - ODOM_TOPIC=/raw_odom
    #command: tail -f /dev/null
